version: "3.9"
services: 
  db:
    image: postgres:13.0
    environment: 
      POSTGRES_USER: Daft
      POSTGRES_PASSWORD: Daft
    command: pg_restore -U Daft -p 5432 -h localhost -d postgres -1 /docker-entrypoint-initdb.d/posts.sql
    volumes: 
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - api
    ports: 
      - "55432:5432"

  fastapi:
    build: .
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://Daft:Daft@db:5432/postgres"

    command: uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 80
    volumes: 
      - ./app:/usr/src/app
    networks:
      - api
    ports: 
      - "8001:80"

networks:
  api:

volumes:
  db:
  fastapi:
    
