version: "3.9"
services: 
  db:
    image: postgres:13.0
    environment: 
      POSTGRES_USER: Daft
      POSTGRES_PASSWORD: Daft
    volumes: postgres:/var/lib/postgresql/data
    ports: 
      - "55432:5432"
volumes:
  db:
    
